/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen_garcia_franklin;

import static examen_garcia_franklin.Garcia_franklin_lab1.alemanes_viven;
import static examen_garcia_franklin.Garcia_franklin_lab1.alumnos_viven;
import static examen_garcia_franklin.Garcia_franklin_lab1.rusos_viven;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Franklin Garcia
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        nodo_alemanes = new DefaultMutableTreeNode("Alemanes");
        nodo_rusos = new DefaultMutableTreeNode("Rusos");
        nodo_alumnos = new DefaultMutableTreeNode("alumnos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_rusos = new javax.swing.JPopupMenu();
        rusos_eliminar = new javax.swing.JMenuItem();
        rusos_modificar = new javax.swing.JMenuItem();
        pop_alemanes = new javax.swing.JPopupMenu();
        alemanes_eliminar = new javax.swing.JMenuItem();
        alemanes_modificar = new javax.swing.JMenuItem();
        pop_alumnos = new javax.swing.JPopupMenu();
        alumnos_eliminar = new javax.swing.JMenuItem();
        alumnos_modificar = new javax.swing.JMenuItem();
        jd_rusos = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jd_alemanes = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jd_alumnos = new javax.swing.JDialog();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbol = new javax.swing.JTree();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();

        rusos_eliminar.setText("eliminar");
        rusos_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rusos_eliminarActionPerformed(evt);
            }
        });
        pop_rusos.add(rusos_eliminar);

        rusos_modificar.setText("modificar");
        rusos_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rusos_modificarActionPerformed(evt);
            }
        });
        pop_rusos.add(rusos_modificar);

        alemanes_eliminar.setText("eliminar");
        alemanes_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alemanes_eliminarActionPerformed(evt);
            }
        });
        pop_alemanes.add(alemanes_eliminar);

        alemanes_modificar.setText("modificar");
        alemanes_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alemanes_modificarActionPerformed(evt);
            }
        });
        pop_alemanes.add(alemanes_modificar);

        alumnos_eliminar.setText("eliminar");
        alumnos_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnos_eliminarActionPerformed(evt);
            }
        });
        pop_alumnos.add(alumnos_eliminar);

        alumnos_modificar.setText("modificar");
        alumnos_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnos_modificarActionPerformed(evt);
            }
        });
        pop_alumnos.add(alumnos_modificar);

        jLabel21.setText("Modificar rusos");

        jLabel22.setText("Nombre");

        jLabel23.setText("ID");

        jLabel24.setText("Edad");

        jLabel25.setText("Rango");

        jLabel26.setText("Resistencia");

        jLabel27.setText("Tipo de arma");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AK-47", "Revolver Navant", "RPG-7" }));

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });

        jButton4.setText("Modificar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_rusosLayout = new javax.swing.GroupLayout(jd_rusos.getContentPane());
        jd_rusos.getContentPane().setLayout(jd_rusosLayout);
        jd_rusosLayout.setHorizontalGroup(
            jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_rusosLayout.createSequentialGroup()
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_rusosLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel21))
                    .addGroup(jd_rusosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_rusosLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField16))
                            .addGroup(jd_rusosLayout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField17))
                            .addGroup(jd_rusosLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField18))
                            .addGroup(jd_rusosLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField19))
                            .addGroup(jd_rusosLayout.createSequentialGroup()
                                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox4, 0, 220, Short.MAX_VALUE)
                                    .addComponent(jTextField15))))))
                .addGap(110, 110, 110))
            .addGroup(jd_rusosLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_rusosLayout.setVerticalGroup(
            jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_rusosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_rusosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel28.setText("Modificar alemanes");

        jLabel29.setText("Alias");

        jLabel30.setText("Edad");

        jLabel31.setText("Casta");

        jLabel32.setText("Resistencia");

        jLabel33.setText("Tipo de arma");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subfusiles MP 40", "Ametralladora MG42", "Pistolas Walther P38" }));

        jButton5.setText("Modificar");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_alemanesLayout = new javax.swing.GroupLayout(jd_alemanes.getContentPane());
        jd_alemanes.getContentPane().setLayout(jd_alemanesLayout);
        jd_alemanesLayout.setHorizontalGroup(
            jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_alemanesLayout.createSequentialGroup()
                .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_alemanesLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel28))
                    .addGroup(jd_alemanesLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(41, 41, 41)
                        .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField23)
                            .addComponent(jTextField22)
                            .addComponent(jTextField21)
                            .addComponent(jComboBox5, 0, 214, Short.MAX_VALUE)
                            .addComponent(jTextField20))))
                .addGap(73, 73, 73))
            .addGroup(jd_alemanesLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_alemanesLayout.setVerticalGroup(
            jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_alemanesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_alemanesLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel30))
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alemanesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jLabel34.setText("Modificar alumnos");

        jLabel35.setText("Numero de cuenta");

        jLabel36.setText("Apodo");

        jLabel37.setText("Edad");

        jLabel38.setText("Resistencias");

        jLabel39.setText("Grado academico");

        jLabel40.setText("Tipo de arma");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discos duros ", "Controles de Wii ", "Laptops " }));

        jButton6.setText("Modificar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_alumnosLayout = new javax.swing.GroupLayout(jd_alumnos.getContentPane());
        jd_alumnos.getContentPane().setLayout(jd_alumnosLayout);
        jd_alumnosLayout.setHorizontalGroup(
            jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_alumnosLayout.createSequentialGroup()
                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_alumnosLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel34))
                    .addGroup(jd_alumnosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_alumnosLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(67, 67, 67)
                                .addComponent(jTextField27))
                            .addGroup(jd_alumnosLayout.createSequentialGroup()
                                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel39))
                                .addGap(38, 38, 38)
                                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_alumnosLayout.createSequentialGroup()
                                        .addComponent(jButton6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField28)
                                    .addComponent(jTextField26)
                                    .addComponent(jTextField24)
                                    .addComponent(jComboBox6, 0, 218, Short.MAX_VALUE)
                                    .addComponent(jTextField25))))))
                .addGap(85, 85, 85))
            .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_alumnosLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(jLabel36)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );
        jd_alumnosLayout.setVerticalGroup(
            jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_alumnosLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel34)
                .addGap(43, 43, 43)
                .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton6)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jd_alumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jd_alumnosLayout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel36)
                    .addContainerGap(314, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Crear Rusos");

        jLabel2.setText("Nombre");

        jLabel3.setText("ID");

        jLabel4.setText("Edad");

        jLabel5.setText("Rango");

        jLabel6.setText("Resistencia");

        jLabel7.setText("Tipo de arma");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AK-47", "Revolver Navant", "RPG-7" }));

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(251, 251, 251)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton1)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Rusos", jPanel1);

        jLabel8.setText("Crear alemanes");

        jLabel9.setText("Alias");

        jLabel10.setText("Edad");

        jLabel11.setText("Casta");

        jLabel12.setText("Resistencia");

        jLabel13.setText("Tipo de arma");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subfusiles MP 40", "Ametralladora MG42", "Pistolas Walther P38" }));

        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                            .addComponent(jTextField6)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton2)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jButton2)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Alemanes", jPanel2);

        jLabel14.setText("Crear alumnos");

        jLabel15.setText("Apodo");

        jLabel16.setText("Numero de cuenta");

        jLabel17.setText("Edad");

        jLabel18.setText("Resistencia");

        jLabel19.setText("Grado academico");

        jLabel20.setText("Tipo de arma");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Discos duros", "Controles de Wii", "Laptops" }));

        jButton3.setText("Guardar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(122, 122, 122)
                                .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(92, 92, 92)
                                .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel19))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox3, 0, 218, Short.MAX_VALUE)
                                        .addComponent(jTextField10)))))))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jButton3)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Alumnos", jPanel3);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Soldados");
        arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbol);

        jButton7.setText("Guardar en binario");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Cargar el binario");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel4);

        jLabel41.setText("Simulacion de batalla ");

        jButton9.setText("Iniciar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane2.setViewportView(ta);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel41))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Simulacion de guerra", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int ed = Integer.parseInt(jTextField3.getText()) * 8;

        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        DefaultMutableTreeNode nodo_raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_ruso;

        String nombre = jTextField1.getText();
        int id = Integer.parseInt(jTextField2.getText());
        int edad = Integer.parseInt(jTextField3.getText());
        int rango = Integer.parseInt(jTextField4.getText());
        int resistencia = Integer.parseInt(jTextField5.getText());
        String tipo_arma = jComboBox1.getSelectedItem().toString();

        if (resistencia >= ed || edad >= 25 && tipo_arma.equals("RPG-7") || edad >= 18) {
            rusos r = new rusos(nombre, id, edad, rango, resistencia, tipo_arma);

            nodo_ruso = new DefaultMutableTreeNode(r);
            nodo_rusos.add(nodo_ruso);
            nodo_raiz.add(nodo_rusos);
            m.reload();
            lista_rusos.add(r);
            jTextField3.setText("");
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            JOptionPane.showMessageDialog(this, "Se agrego");
        } else {
            JOptionPane.showMessageDialog(this, "La resistencia no es 8 veces mayor a la edad \n"
                    + "o no pueden llevar una RPG-7 por que es menor de 25 años \n"
                    + "o el soldado es menor de 18 años");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        String alias = jTextField6.getText();
        int edad = Integer.parseInt(jTextField7.getText());
        int ed = edad * 8;
        String casta = jTextField8.getText();
        int resistencia = Integer.parseInt(jTextField9.getText());
        String tipo_arma = jComboBox2.getSelectedItem().toString();

        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        DefaultMutableTreeNode nodo_raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_aleman;

        if (resistencia >= ed || edad > 0) {
            alemanes a = new alemanes(alias, edad, casta, resistencia, tipo_arma);
            nodo_aleman = new DefaultMutableTreeNode(a);
            nodo_alemanes.add(nodo_aleman);
            nodo_raiz.add(nodo_alemanes);
            lista_alemanes.add(a);
            m.reload();
            lista_alemanes.add(a);
            JOptionPane.showMessageDialog(this, "Se agrego");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "La edad no es mayor a o 0\n"
                    + "resistencia no es 8 veces mayor que la edad");
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        String apodo = jTextField10.getText();
        int numero_cuenta = Integer.parseInt(jTextField11.getText());
        int edad = Integer.parseInt(jTextField12.getText());
        int resistencia = Integer.parseInt(jTextField13.getText());
        String tipo_arma = jComboBox3.getSelectedItem().toString();
        String grado_academico = jTextField14.getText();

        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        DefaultMutableTreeNode nodo_raiz = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_alumno;
        if (resistencia >= edad * 8 && edad >= 16) {
            alumnos a = new alumnos(grado_academico, apodo, numero_cuenta, edad, resistencia, tipo_arma);
            nodo_alumno = new DefaultMutableTreeNode(a);
            nodo_alumnos.add(nodo_alumno);
            nodo_raiz.add(nodo_alumnos);
            lista_alumnos.add(a);
            m.reload();
            JOptionPane.showMessageDialog(this, "Se agrego");
            jTextField10.setText("");
            jTextField11.setText("");
            jTextField12.setText("");
            jTextField13.setText("");
            jTextField14.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Edad baja de 16 \n"
                    + "Resistencia no es 8 veces la edad");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolMouseClicked
        if (evt.isMetaDown()) {
            int row = arbol.getClosestRowForLocation(evt.getX(), evt.getY());
            arbol.setSelectionRow(row);
            Object v1 = arbol.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof rusos) {
                ruso_seleccionado = (rusos) nodo_seleccionado.getUserObject();
                pop_rusos.show(evt.getComponent(), evt.getX(), evt.getY());
            }

            if (nodo_seleccionado.getUserObject() instanceof alemanes) {
                aleman_seleccionado = (alemanes) nodo_seleccionado.getUserObject();
                pop_alemanes.show(evt.getComponent(), evt.getX(), evt.getY());
            }
            if (nodo_seleccionado.getUserObject() instanceof alumnos) {
                alumno_seleccionado = (alumnos) nodo_seleccionado.getUserObject();
                pop_alumnos.show(evt.getComponent(), evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_arbolMouseClicked

    private void rusos_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rusos_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_rusos_eliminarActionPerformed

    private void alemanes_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alemanes_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_alemanes_eliminarActionPerformed

    private void alumnos_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnos_eliminarActionPerformed
        DefaultTreeModel m = (DefaultTreeModel) arbol.getModel();
        m.removeNodeFromParent(nodo_seleccionado);
        m.reload();
    }//GEN-LAST:event_alumnos_eliminarActionPerformed

    private void rusos_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rusos_modificarActionPerformed
        jd_rusos.setModal(true);
        jd_rusos.setLocationRelativeTo(this);
        jd_rusos.pack();
        jd_rusos.setVisible(true);
    }//GEN-LAST:event_rusos_modificarActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String nombre = jTextField15.getText();
        int id = Integer.parseInt(jTextField16.getText());
        int edad = Integer.parseInt(jTextField17.getText());
        int rango = Integer.parseInt(jTextField18.getText());
        int resistencia = Integer.parseInt(jTextField19.getText());
        String tipo_arma = jComboBox4.getSelectedItem().toString();

        ruso_seleccionado.setEdad(edad);
        ruso_seleccionado.setId(id);
        ruso_seleccionado.setNombre(nombre);
        ruso_seleccionado.setRango(rango);
        ruso_seleccionado.setResistencia(resistencia);
        ruso_seleccionado.setTipo_arma(tipo_arma);
        JOptionPane.showMessageDialog(this, "Se modifico");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        String alias = jTextField20.getText();
        int edad = Integer.parseInt(jTextField21.getText());
        String casta = jTextField22.getText();
        int resistencia = Integer.parseInt(jTextField23.getText());
        String tipo_arma = jComboBox5.getSelectedItem().toString();

        aleman_seleccionado.setAlias(alias);
        aleman_seleccionado.setCasta(casta);
        aleman_seleccionado.setEdad(edad);
        aleman_seleccionado.setResistencia(resistencia);
        aleman_seleccionado.setTipo_arma(tipo_arma);
        JOptionPane.showMessageDialog(this, "Se modifico");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
    }//GEN-LAST:event_jButton5MouseClicked

    private void alemanes_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alemanes_modificarActionPerformed
        jd_alemanes.setModal(true);
        jd_alemanes.setLocationRelativeTo(this);
        jd_alemanes.pack();
        jd_alemanes.setVisible(true);
    }//GEN-LAST:event_alemanes_modificarActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        String apodo = jTextField24.getText();
        int numero_cuenta = Integer.parseInt(jTextField25.getText());
        int edad = Integer.parseInt(jTextField26.getText());
        int resistencia = Integer.parseInt(jTextField27.getText());
        String tipo_arma = jComboBox6.getSelectedItem().toString();
        String grado_academico = jTextField28.getText();

        alumno_seleccionado.setApodo(apodo);
        alumno_seleccionado.setEdad(edad);
        alumno_seleccionado.setGrado_academico(grado_academico);
        alumno_seleccionado.setNumero_cuenta(numero_cuenta);
        alumno_seleccionado.setResistencia(resistencia);
        alumno_seleccionado.setTipo_arma(tipo_arma);
        JOptionPane.showMessageDialog(this, "Se modifico");
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");
    }//GEN-LAST:event_jButton6MouseClicked

    private void alumnos_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnos_modificarActionPerformed
        jd_alumnos.setModal(true);
        jd_alemanes.setLocationRelativeTo(this);
        jd_alemanes.pack();
        jd_alemanes.setVisible(true);
    }//GEN-LAST:event_alumnos_modificarActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        adminArbol a = new adminArbol("./disco.cbm");
        a.setModelo((DefaultTreeModel) arbol.getModel());
        a.escribirArchivo();
        JOptionPane.showMessageDialog(this, "se guardo");
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        adminArbol a = new adminArbol("./disco.cbm");
        a.cargarArchivo(arbol);

    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        boolean vive = true;
        int turno = 0;
        int daño = 0;
        while (vive = true) {
            if (turno == 0) {
                ta.append("Turno de rusos \n");
                int res = 0;
                for (alemanes a : lista_alemanes) {
                    for (int i = 0; i < lista_rusos.size(); i++) {
                        ta.append("Atacando a alemania \n");
                        if (lista_rusos.get(i).getTipo_arma().equals("AK-47")) {
                            res = a.getResistencia() - 27;
                            a.setResistencia(res);
                            System.out.println(res);
                        } else if (lista_rusos.get(i).getTipo_arma().equals("Revolver Navant")) {
                            res = a.getResistencia() - 13;
                            a.setResistencia(res);
                            System.out.println(res);
                        } else if (lista_rusos.get(i).getTipo_arma().equals("RPG-7")) {
                            res = a.getResistencia() - 57;
                            a.setResistencia(res);
                            System.out.println(res);
                        }
                    }
                }

                for (alumnos a : lista_alumnos) {
                    for (int i = 0; i < lista_rusos.size(); i++) {
                        ta.append("atacando a alumnos \n");
                        if (lista_rusos.get(i).getTipo_arma().equals("AK-47")) {
                            res = a.getResistencia() - 27;
                            a.setResistencia(res);
                        } else if (lista_rusos.get(i).getTipo_arma().equals("Revolver Navant")) {
                            res = a.getResistencia() - 13;
                            a.setResistencia(res);

                        } else if (lista_rusos.get(i).getTipo_arma().equals("RPG-7")) {
                            res = a.getResistencia() - 57;
                            a.setResistencia(res);

                        }
                    }
                }
                turno++;
                //fin 
            } else if (turno == 1) {
                ta.append("Turno de alemanes \n");

                int res = 0;
                for (rusos r : lista_rusos) {
                    for (int i = 0; i < lista_alemanes.size(); i++) {
                        ta.append("atacando rusos \n");
                        if (lista_alemanes.get(i).getTipo_arma().equals("MP 40")) {
                            res = r.getResistencia() - 25;
                            r.setResistencia(res);
                        } else if (lista_alemanes.get(i).getTipo_arma().equals("Ametralladora MG42")) {
                            res = r.getResistencia() - 32;
                            r.setResistencia(res);
                        } else if (lista_alemanes.get(i).getTipo_arma().equals("Pistolas Walther P38")) {
                            res = r.getResistencia() - 11;
                            r.setResistencia(res);
                        }
                    }
                }
                for (alumnos r : lista_alumnos) {
                    for (int i = 0; i < lista_alemanes.size(); i++) {
                        ta.append("atacando a alumnos \n");
                        if (lista_alemanes.get(i).getTipo_arma().equals("MP 40")) {
                            res = r.getResistencia() - 25;
                            r.setResistencia(res);
                        } else if (lista_alemanes.get(i).getTipo_arma().equals("Ametralladora MG42")) {
                            res = r.getResistencia() - 32;
                            r.setResistencia(res);
                        } else if (lista_alemanes.get(i).getTipo_arma().equals("Pistolas Walther P38")) {
                            res = r.getResistencia() - 11;
                            r.setResistencia(res);
                        }
                    }
                }
                turno++;
            } else if (turno == 2) {
                ta.setText("Turno de alumnos \n");
                int res = 0;
                for (rusos r : lista_rusos) {
                    for (int i = 0; i < lista_alumnos.size(); i++) {
                        ta.append("atacando a rusos \n");
                        if (lista_alumnos.get(i).getTipo_arma().equals("Discos duros")) {
                            res = r.getResistencia() - 23;
                            r.setResistencia(res);
                        } else if (lista_alumnos.get(i).getTipo_arma().equals("Controles de Wii")) {
                            res = r.getResistencia() - 47;
                            r.setResistencia(res);
                        } else if (lista_alumnos.get(i).getTipo_arma().equals("Laptos")) {
                            res = r.getResistencia() - 76;
                            r.setResistencia(res);
                        }
                    }
                }
                for (alemanes r : lista_alemanes) {
                    for (int i = 0; i < lista_alumnos.size(); i++) {
                        ta.append("atacando a alemanes \n");

                        if (lista_alumnos.get(i).getTipo_arma().equals("Discos duros")) {
                            res = r.getResistencia() - 23;
                            r.setResistencia(res);
                        } else if (lista_alumnos.get(i).getTipo_arma().equals("Controles de Wii")) {
                            res = r.getResistencia() - 47;
                            r.setResistencia(res);
                        } else if (lista_alumnos.get(i).getTipo_arma().equals("Laptos")) {
                            res = r.getResistencia() - 76;
                            r.setResistencia(res);
                        }
                    }
                }
                turno = 0;
            }
            try {
                if (!lista_rusos.isEmpty()) {
                    int res_muerta = 0;
                    for (rusos r : lista_rusos) {
                        if (r.getResistencia() <= 0) {
                            lista_rusos.remove(r);
                        }
                        res_muerta++;
                    }
                }
            } catch (Exception e) {
                ta.append("gano rusia");
                break;
            }

            try {
                if (!lista_alemanes.isEmpty()) {
                    int conf = 0;
                    for (alemanes ap : lista_alemanes) {
                        if (ap.getResistencia() <= 0) {
                            lista_alemanes.remove(ap);
                        }
                        conf++;
                    }
                }
            } catch (Exception e) {
                ta.append("gano alemania");
                break;
            }
            try {
                if (!lista_alumnos.isEmpty()) {
                    int conv = 0;
                    for (alumnos a : lista_alumnos) {
                        if (a.getResistencia() <= 0) {
                            lista_alumnos.remove(a);
                        }
                        conv++;
                    }
                }
            } catch (Exception e) {
               ta.append("gabo alumnos");
                break;
            }
            if (alemanes_viven(lista_alemanes) == false && alumnos_viven(lista_alumnos) == false) {
                ta.append("gano rusia \n");
                vive = false;

            } else if (rusos_viven(lista_rusos) == false && alumnos_viven(lista_alumnos) == false) {
                ta.append("gano alemanes \n");
                vive = false;
            } else if (rusos_viven(lista_rusos) == false && alemanes_viven(lista_alemanes) == false) {
                ta.append("gano alumnos \n");
                vive = false;
            }
        }

    }//GEN-LAST:event_jButton9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static boolean rusos_viven(ArrayList rusos) {
        if (rusos.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public static boolean alemanes_viven(ArrayList alemanes) {
        if (alemanes.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public static boolean alumnos_viven(ArrayList alumnos) {
        if (alumnos.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Linux".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alemanes_eliminar;
    private javax.swing.JMenuItem alemanes_modificar;
    private javax.swing.JMenuItem alumnos_eliminar;
    private javax.swing.JMenuItem alumnos_modificar;
    private javax.swing.JTree arbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JDialog jd_alemanes;
    private javax.swing.JDialog jd_alumnos;
    private javax.swing.JDialog jd_rusos;
    private javax.swing.JPopupMenu pop_alemanes;
    private javax.swing.JPopupMenu pop_alumnos;
    private javax.swing.JPopupMenu pop_rusos;
    private javax.swing.JMenuItem rusos_eliminar;
    private javax.swing.JMenuItem rusos_modificar;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
    DefaultMutableTreeNode nodo_rusos;
    DefaultMutableTreeNode nodo_alemanes;
    DefaultMutableTreeNode nodo_alumnos;
    DefaultMutableTreeNode nodo_seleccionado;

    alemanes aleman_seleccionado;
    rusos ruso_seleccionado;
    alumnos alumno_seleccionado;

    ArrayList<rusos> lista_rusos = new ArrayList();
    ArrayList<alemanes> lista_alemanes = new ArrayList();
    ArrayList<alumnos> lista_alumnos = new ArrayList();
}
